---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by user.
--- DateTime: 2023/6/21 11:06
---

print("hello world!")

function helloFunction()
    print("helloFunction")
    print("a=", a)

end

helloFunction()
a = 0;
helloFunction()

function count(limit)
    sum = 0
    for i = 1, limit do
        sum = sum + i
    end
    print(sum)
    return limit, sum
end

count(100)
print(count(10))
--[[
--]]
function addAll(...)
    sum = 0
    args = { ... }
    for i in ipairs(args) do
        sum = sum + i
    end
    print(sum)
    return table.concat(args, ","), "sum=", sum
end
print(addAll(1, 2, 3))

function addAll2(...)
    sum = 0
    for i = 1, select('#', ...) do
        sum = sum + select(i, ...)
    end
    print("sum=", sum)
end
addAll2(1, 2, 3, 4)
a = 5
b = 2
print(a / b)
--5.3 版本后才有
--print(a // b)

print("12".."34")
str = "12".."34"
print(#str)

